# Generated by Django 5.2.10 on 2026-01-17 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_delete_order_remove_returnrequest_order_item_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_new_arrival',
            field=models.BooleanField(default=False, help_text="Check this to show in 'New Arrivals' section"),
        ),
        migrations.AlterField(
            model_name='product',
            name='discount_label',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
