# Generated by Django 5.2.10 on 2026-01-19 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_is_new_arrival_alter_product_discount_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='discount_label',
            field=models.CharField(blank=True, help_text="e.g. 'UNDER 499'", max_length=50),
        ),
    ]
