# Generated by Django 5.2.10 on 2026-01-19 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_image_category_icon_category_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcategory',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='SubCategory',
        ),
    ]
