# Generated by Django 5.2.10 on 2026-01-19 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='mobile',
            field=models.CharField(max_length=15, null=True, unique=True),
        ),
    ]
